name: Git Download and Upload Files

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:  
      - 'file.txt' 

env:
  SERVER_URL: "${{ secrets.CITMS_SERVER_URL }}"
  SERVER_API_KEY: "${{ secrets.CITMS_SERVER_API_KEY }}"

jobs:

  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    # 增加可用磁盘空间
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:

        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        # 如果空间还是不够用，可以把以下开启，清理出更多空间
        # remove-android: 'true'
        # remove-codeql: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: Free up disk space complete
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Download File And Upload File to Server  
      run: |
        # 数据预处理
        while IFS= read -r line; do
            # 忽略空行与注释
            [[ -z "$line" ]] && continue
            if echo "$line" | grep -q '^\s*#'; then
                continue
            fi
            
            # 从url地址中获取文件名，例如https://github.com/CrazyJson/docker_image_pusher/archive/refs/heads/main.zip  文件名为main.zip 
            filename=$(basename "$line")

            # 从url地址中获取git用户名 CrazyJson
            username=$(echo "$line" | awk -F'/' '{print  $4}' )

            # 从url地址中获取仓库地址 docker_image_pusher
            repname=$(echo "$line" | awk -F'/' '{print  $5}' )

            # 从url地址中获取本地目录地址 CrazyJson/docker_image_pusher
            download_temp=$(echo "$line" | awk -F'/' '{print $4"/"$5}')
            mkdir -p $download_temp

            real_filename="${download_temp}"/"${filename}"
            curl -L -o "$real_filename" "$line"  

            # 检查文件是否成功下载
            if [ $? -eq 0 ]; then  
              # 上传文件
              echo "开始上传文件$filename"
              curl -X POST -F "file=@$real_filename" -H "Authorization: Bearer $SERVER_API_KEY" "$SERVER_URL/upload?username=$username&repname=$repname"  
              # 清理文件
              rm -f "$real_filename"  
            else  
              echo "Failed to download $filename"  
            fi    
        done < file.txt
      
